# Generated by Django 3.0.2 on 2020-02-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_booking_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
    ]
