# Generated by Django 3.0.2 on 2020-01-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_auto_20200128_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
