# Generated by Django 3.0.2 on 2020-02-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_auto_20200128_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp']},
        ),
    ]
