# Generated by Django 3.0.2 on 2020-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200127_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/HIT_logo.png', upload_to='profile/'),
        ),
    ]
