# Generated by Django 3.0.2 on 2020-06-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200219_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
