# Generated by Django 3.0.2 on 2020-06-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='total_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
