# Generated by Django 3.0.2 on 2020-06-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_meal_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
