# Generated by Django 3.0.2 on 2020-01-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20200126_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='image',
            field=models.FileField(upload_to='timetables/'),
        ),
    ]
