# Generated by Django 3.0.2 on 2020-01-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200126_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='time',
            field=models.TimeField(),
        ),
    ]
