# Generated by Django 3.0.2 on 2020-02-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20200127_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_code',
            field=models.CharField(default='BEC413', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='gpa',
            field=models.CharField(default='2.4', max_length=50),
            preserve_default=False,
        ),
    ]
