# Generated by Django 3.0.2 on 2020-02-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20200219_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='gpa',
        ),
    ]
